[Interface]
Address = 10.10.0.2/24
PrivateKey = (leerás de /etc/wireguard/private.key con sudo)

[Peer]
# Oracle B.O.
PublicKey = ORACLE_PUBKEY_PENDIENTE
Endpoint = ORACLE_IP_PENDIENTE:51820
AllowedIPs = 10.10.0.1/32
PersistentKeepalive = 25
